[build-system]
requires = [
    "setuptools>=80.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "docassemble.MichiganNameChange"
version = "0.1.0"
description = "Michigan Name Change Tools"
readme = "README.md"
authors = [
    { name = "Michigan Legal Help", email = "ekressmiller@lsscm.org" },
]
dependencies = []
license = "MIT"
license-files = [
    "LICENSE",
]

[project.urls]
Homepage = "https://docassemble.org"

[tool.setuptools.packages.find]
where = [
    ".",
]
